/** Official taluka names for Tamil Nadu districts (2024 administrative divisions). */
export const DISTRICT_TALUKAS: Record<string, string[]> = {
  ariyalur: ['Ariyalur', 'Jayankondam', 'Sendurai', 'Udayarpalayam'],
  chengalpattu: ['Chengalpattu', 'Cheyyur', 'Madurantakam', 'Pallavaram', 'Tambaram', 'Thirukazhukundram', 'Thiruporur'],
  chennai: ['Ambattur', 'Alandur', 'Egmore', 'Guindy', 'Madhavaram', 'Mylapore', 'Perambur', 'Sholinganallur', 'Tondiarpet'],
  coimbatore: ['Mettupalayam', 'Coimbatore North', 'Coimbatore South', 'Sulur', 'Pollachi', 'Valparai'],
  cuddalore: ['Cuddalore', 'Chidambaram', 'Kurinjipadi', 'Panruti', 'Virudhachalam'],
  dharmapuri: ['Dharmapuri', 'Harur', 'Karimangalam', 'Nallampalli', 'Palacode', 'Pennagaram'],
  dindigul: ['Athoor', 'Dindigul', 'Kodaikanal', 'Natham', 'Nilakkottai', 'Oddanchatram', 'Palani', 'Vedasandur'],
  erode: ['Anthiyur', 'Bhavani', 'Erode', 'Gobichettipalayam', 'Modakkurichi', 'Perundurai', 'Sathiyamangalam', 'Talavadi'],
  kallakurichi: ['Chinnasalem', 'Kallakurichi', 'Kalrayan Hills', 'Rishivandiyam', 'Sankarapuram', 'Thiagadurgam', 'Ulundurpet', 'Vadakkanandal'],
  kanchipuram: ['Kanchipuram', 'Sriperumbudur', 'Uthiramerur', 'Walajabad'],
  kanyakumari: ['Agastheeswaram', 'Kalkulam', 'Killiyoor', 'Thiruvattar', 'Thovala', 'Vilavancode'],
  karur: ['Aravakurichi', 'Kadavur', 'Karur', 'Krishnarayapuram', 'Kulithalai', 'Manmangalam', 'Pugalur'],
  krishnagiri: ['Bargur', 'Hosur', 'Kaveripattinam', 'Krishnagiri', 'Pochampalli', 'Shoolagiri', 'Uthangarai'],
  madurai: ['Madurai North', 'Madurai South', 'Melur', 'Peraiyur', 'Thirumangalam', 'Usilampatti', 'Vadipatti'],
  mayiladuthurai: ['Kuthalam', 'Mayiladuthurai', 'Sirkazhi', 'Tharangambadi'],
  nagapattinam: ['Kilvelur', 'Kuthalam', 'Mayiladuthurai', 'Nagapattinam', 'Sirkazhi', 'Tharangambadi', 'Thirukkuvalai', 'Vedaranyam'],
  namakkal: ['Kolli Hills', 'Kumarapalayam', 'Mohanur', 'Namakkal', 'Paramathi-Velur', 'Rasipuram', 'Senthamangalam', 'Tiruchengode'],
  nilgiris: ['Coonoor', 'Gudalur', 'Kotagiri', 'Kundah', 'Panthalur', 'Udhagamandalam'],
  perambalur: ['Alathur', 'Kunnam', 'Perambalur', 'Veppanthattai'],
  pudukkottai: ['Alangudi', 'Aranthangi', 'Avudaiyarkoil', 'Gandarvakottai', 'Iluppur', 'Karambakudi', 'Kulathur', 'Manamelkudi', 'Ponnamaravathi', 'Pudukkottai', 'Thirumayam', 'Viralimalai'],
  ramanathapuram: ['Kadaladi', 'Kamuthi', 'Mandapam', 'Paramakudi', 'Ramanathapuram', 'Rameswaram', 'Tiruvadanai'],
  ranipet: ['Arakkonam', 'Arcot', 'Kalavai', 'Nemili', 'Sholinghur', 'Walajah'],
  salem: ['Attur', 'Edappadi', 'Gangavalli', 'Mettur', 'Omalur', 'Salem', 'Sankagiri', 'Valapady', 'Yercaud'],
  sivaganga: ['Devakottai', 'Ilayangudi', 'Karaikudi', 'Manamadurai', 'Singampunari', 'Sivaganga', 'Thiruppathur', 'Thiruppuvanam'],
  tenkasi: ['Alangulam', 'Kadayanallur', 'Sankarankovil', 'Shenkottai', 'Tenkasi', 'Veerakeralamputhur'],
  thanjavur: ['Budalur', 'Kumbakonam', 'Orathanadu', 'Papanasam', 'Pattukkottai', 'Peravurani', 'Thanjavur', 'Thiruvaiyaru', 'Thiruvidaimarudur'],
  theni: ['Andipatti', 'Bodinayakanur', 'Periyakulam', 'Theni', 'Uthamapalayam'],
  thoothukudi: ['Eral', 'Ettayapuram', 'Kayathar', 'Kovilpatti', 'Ottapidaram', 'Sathankulam', 'Srivaikundam', 'Thoothukudi', 'Tiruchendur', 'Vilathikulam'],
  tiruchirappalli: ['Lalgudi', 'Manachanallur', 'Manapparai', 'Marungapuri', 'Musiri', 'Srirangam', 'Thiruverumbur', 'Tiruchirappalli'],
  tirunelveli: ['Ambasamudram', 'Cheranmahadevi', 'Manur', 'Nanguneri', 'Palayamkottai', 'Radhapuram', 'Shenkottai', 'Tirunelveli'],
  tirupathur: ['Ambur', 'Natrampalli', 'Tirupathur', 'Vaniyambadi'],
  tiruppur: ['Avinashi', 'Dharapuram', 'Kangeyam', 'Madathukulam', 'Palladam', 'Tiruppur', 'Udumalaipettai'],
  tiruvallur: ['Avadi', 'Gummidipoondi', 'Pallipattu', 'Ponneri', 'Poonamallee', 'R.K. Pet', 'Tiruttani', 'Tiruvallur', 'Uthukkottai'],
  tiruvannamalai: ['Arani', 'Chengam', 'Cheyyar', 'Jamunamarathur', 'Keelpennathur', 'Polur', 'Thandarampattu', 'Tiruvannamalai', 'Vandavasi', 'Vembakkam'],
  tiruvarur: ['Kodavasal', 'Mannargudi', 'Nannilam', 'Needamangalam', 'Thiruthuraipoondi', 'Thiruvarur', 'Valangaiman'],
  vellore: ['Anaicut', 'Arakkonam', 'Arcot', 'Gudiyattam', 'Katpadi', 'Pernambut', 'Vellore', 'Walajah'],
  viluppuram: ['Gingee', 'Kallakurichi', 'Marakkanam', 'Sankarapuram', 'Thiruvennainallur', 'Tindivanam', 'Vanur', 'Vikravandi', 'Viluppuram'],
  virudhunagar: ['Aruppukkottai', 'Kariapatti', 'Rajapalayam', 'Sattur', 'Sivakasi', 'Srivilliputhur', 'Tiruchuli', 'Virudhunagar', 'Watrap'],
};

/** Map org-path segment codes to registry keys. */
export const ORG_PATH_ALIASES: Record<string, string> = {
  coimbatore: 'coimbatore',
  cbe: 'coimbatore',
  salem: 'salem',
  chennai: 'chennai',
  madurai: 'madurai',
  erode: 'erode',
  tiruppur: 'tiruppur',
  nilgiris: 'nilgiris',
  dindigul: 'dindigul',
  trichy: 'tiruchirappalli',
  tiruchirappalli: 'tiruchirappalli',
  thanjavur: 'thanjavur',
};

export function formatDistrictName(key: string): string {
  const special: Record<string, string> = {
    tiruchirappalli: 'Tiruchirappalli',
    tirunelveli: 'Tirunelveli',
    tiruvallur: 'Tiruvallur',
    tiruvannamalai: 'Tiruvannamalai',
    tiruvarur: 'Tiruvarur',
    tiruppur: 'Tiruppur',
    tirupathur: 'Tirupathur',
    thoothukudi: 'Thoothukudi',
    chengalpattu: 'Chengalpattu',
    kallakurichi: 'Kallakurichi',
    kanchipuram: 'Kanchipuram',
    kanyakumari: 'Kanyakumari',
    krishnagiri: 'Krishnagiri',
    mayiladuthurai: 'Mayiladuthurai',
    nagapattinam: 'Nagapattinam',
    ramanathapuram: 'Ramanathapuram',
    virudhunagar: 'Virudhunagar',
    viluppuram: 'Viluppuram',
  };
  return special[key] ?? key.charAt(0).toUpperCase() + key.slice(1);
}
